name: My first workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome Message
          run: eacho "My first Action welcome amol"
        - name: List Files
          run: ls
        - name: Read File
          run: cat README.md 
