name: My first workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4          
        - name: List File & Read 
          run: |
            echo "My first Action welcome amol"
            ls -lrt
            cat README.md
        - name: Pint ASCII Artwork
          run: cowsay -f dragon "Here be dragons!" > dragon.txt
        # - name: List Files
        #   run: ls
        # - name: Read File
        #   run: cat README.md 
