name: Generate Ascii Artwork

on: push

jobs:
    generate_artwork:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls -lart
            - name: Excute Shell script
              run: |
                chmod +x
                ./scii-script.sh
            